add_rules("mode.debug", "mode.release")
add_requires("cli11")
add_requires("dbg-macro")
add_requires("magic_enum")
add_requires("toml++")

target("lcj++")
    set_kind("binary")
    add_files("src/*.cpp")
    add_files("src/file_handling/*.cpp")
    add_packages("cli11")
    add_packages("dbg-macro")
    add_packages("magic_enum")
    add_packages("toml++")

set_languages("c++23")
set_toolchains("clang")
set_warnings("all", "extra")
