add_rules("mode.debug", "mode.release")
set_defaultmode("debug")
add_requires("cli11")
add_requires("dbg-macro")
add_requires("magic_enum")
add_requires("toml++")
add_requires("reproc", { configs = { reprocxx = true } })

target("lcj++")
set_kind("binary")
add_files("src/*.cpp")
add_files("src/file_handling/*.cpp")
add_files("src/sandbox/*.cpp")
add_packages("cli11", "dbg-macro", "magic_enum", "toml++", "reproc")

set_languages("c++23")
set_toolchains("clang")
set_warnings("all", "extra")
